using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HYC.Framework.Config.Editor
{
    /// <summary>
    /// Editor pipeline that turns a spreadsheet into:
    ///  - a generated C# <c>[BlobGenerate]</c> row struct (blittable);
    ///
    /// Spreadsheet conventions (see <see cref="ExcelReader"/>):
    ///   row 0 = field names,
    ///   row 1 = types (<c>long/int/float/double/bool/string</c>),
    ///   row 2 = comments,
    ///   row 3.. = data.
    /// </summary>
    public static class ConfigGenerator
    {
        private class Column
        {
            public string Name;
            public string Type;
        }

        public static string ToTitle(string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return "Config";
            var parts = name.Split(new[] { ' ', '_' }, System.StringSplitOptions.RemoveEmptyEntries);
            for (int i = 0; i < parts.Length; i++)
            {
                if (parts[i].Length == 0) continue;
                parts[i] = char.ToUpperInvariant(parts[i][0]) + parts[i].Substring(1);
            }
            var joined = string.Concat(parts);
            return joined.Length > 0 ? joined : "Config";
        }

        public static string GenerateStruct(string sheetName, IReadOnlyList<string[]> rows)
        {
            if (rows.Count < 3) return string.Empty;
            var headers = rows[0];
            var types = rows[1];

            var cols = new List<Column>();
            for (int i = 0; i < headers.Length; i++)
            {
                var headerName = headers[i];
                if (string.IsNullOrWhiteSpace(headerName)) continue;
                string type = (i < types.Length) ? MapType(types[i]) : "long";
                cols.Add(new Column { Name = SanitizeName(headerName), Type = type });
            }
            if (cols.Count == 0) return string.Empty;

            var name = ToTitle(sheetName) + "Config";
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> by HYC.Framework.Config.ConfigGenerator </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using Unity.Entities;");
            sb.AppendLine();
            sb.AppendLine("namespace HYC.Framework.Config.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    [HYC.Framework.Config.BlobGenerate]");
            sb.AppendLine("    public struct " + name + " : IComponentData, System.IEquatable<" + name + ">");
            sb.AppendLine("    {");
            foreach (var c in cols) sb.AppendLine("        public " + c.Type + " " + c.Name + ";");
            sb.AppendLine();
            sb.AppendLine("        public bool Equals(" + name + " other) => GetHashCode() == other.GetHashCode();");
            sb.AppendLine("        public override bool Equals(object obj) => obj is " + name + " o && Equals(o);");
            sb.AppendLine("        public override int GetHashCode()");
            sb.AppendLine("        {");
            sb.AppendLine("            unchecked");
            sb.AppendLine("            {");
            sb.AppendLine("                int hash = 17;");
            foreach (var c in cols)
            {
                if (c.Type == "string")
                    sb.AppendLine("                hash = hash * 31 + (StringComparer.Ordinal.GetHashCode(this." + c.Name + " ?? string.Empty));");
                else
                    sb.AppendLine("                hash = hash * 31 + this." + c.Name + ".GetHashCode();");
            }
            sb.AppendLine("                return hash;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string SanitizeName(string raw)
        {
            var sb = new StringBuilder();
            foreach (var ch in raw)
            {
                if (char.IsLetterOrDigit(ch)) sb.Append(ch);
            }
            if (sb.Length == 0) sb.Append("Field");
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        private static string MapType(string t)
        {
            switch (t?.Trim().ToLowerInvariant())
            {
                case "long":
                case "int64":
                    return "long";
                case "int":
                case "int32":
                case "integer":
                    return "int";
                case "float":
                    return "float";
                case "double":
                    return "double";
                case "bool":
                case "boolean":
                    return "bool";
                case "string":
                case "text":
                    return "string";
                default:
                    return "long";
            }
        }
    }
}